Macros feature/create table derive macros
ideal-world/tardis pull request #25
Opened 2023-02-26 13:42 UTC by RWDai

not completed

2023-02-27 03:59 UTC, RWDai commented
Minimum function available

2023-04-18 01:45 UTC, gudaoxuri requested changes

2023-04-18 01:45 UTC, gudaoxuri commented on examples/macros_examples/src/example_for_derive_create_tabled.rs
> +//run `cargo expand example_for_derive_create_tabled > derive_create_tabled_expand.rs` \
加空格

2023-04-18 01:45 UTC, gudaoxuri commented on examples/macros_examples/src/example_for_derive_table_index.rs
> +//run `cargo expand example_for_derive_table_index > derive_create_index_expand.rs`
加空格

2023-04-18 01:45 UTC, gudaoxuri commented on examples/macros_examples/src/example_for_derive_table_index.rs
> +pub struct Model {
确保bios/spi-stats下各索引都可支持

2023-04-18 01:45 UTC, gudaoxuri commented on tardis-macros/Cargo.toml
> +reldb-postgres=[]
空格

2023-04-18 01:45 UTC, gudaoxuri commented on tardis-macros/Cargo.toml
> +darling={verion="1"}
空格

2023-04-18 01:45 UTC, gudaoxuri commented on tardis-macros/src/lib.rs
>  #[proc_macro_attribute]
去掉

2023-04-18 01:45 UTC, gudaoxuri commented on examples/macros_examples/src/example_for_derive_create_tabled.rs
> +use tardis::basic::dto::TardisContext;
文件名 ...tabled.rs 不是习惯用语且无此单词

2023-04-18 01:45 UTC, gudaoxuri commented on examples/macros_examples/src/example_for_derive_create_tabled.rs
> +    ///Call the method automatically generated by DeriveCreateTable macros
空格

2023-04-18 01:45 UTC, gudaoxuri commented on tardis-macros/src/lib.rs
> +pub fn TardisCreateTable(input: TokenStream) -> TokenStream {
为什么要用snake case？

2023-04-18 01:45 UTC, gudaoxuri commented on tardis-macros/src/lib.rs
> +#[proc_macro_derive(DeriveCreateTable, attributes(sea_orm))]
DeriveCreateTable 与 DeriveTableIndex 词法不统一，建议：
TardisCreateTable / TardisCreateIndex

2023-04-18 01:45 UTC, gudaoxuri commented on tardis-macros/src/tardis_create_index.rs
> +fn default_index_id() -> String {
为避免重复，默认索引建议使用``idx_随机数``

2023-04-18 01:45 UTC, gudaoxuri commented on tardis/Cargo.toml
> +tardis-macros = { version = "0.1.0-alpha34", path = "../tardis-macros", optional = true , features =["reldb-postgres"]}
空格

2023-04-18 01:45 UTC, gudaoxuri commented on tardis/Cargo.toml
> +tardis-macros = { version = "0.1.0-alpha34", path = "../tardis-macros", optional = true , features =["reldb-postgres"]}
为什么默认加了 reldb-postgres

2023-04-18 01:45 UTC, gudaoxuri commented on tardis-macros/src/lib.rs
> +pub fn TardisCreateTable(input: TokenStream) -> TokenStream {
要加上  reldb-mysql / postgresql 的features， 下同

2023-05-03 11:35 UTC, merged